package com.example.Appointment.System.model.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
@Schema(name="Diagnostic", description = "DTO representing diagnostic center details.")
public class DiagnosticDTO {

    @Schema(
            description = "Unique identifier of the diagnostic center. Not required during creation; generated by the system.",
            example = "1",
            accessMode = Schema.AccessMode.READ_ONLY
    )
    private Long labId;

    @Schema(
            description = "Name of the diagnostic center.",
            example = "MediTech Diagnostic Center",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String diagnosticCenterName;

    @Schema(
            description = "Country where the diagnostic center is located.",
            example = "Bangladesh",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String country;

    @Schema(
            description = "City where the diagnostic center is located.",
            example = "Dhaka",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String city;

    @Schema(
            description = "Postal/ZIP code of the diagnostic center.",
            example = "1209",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String zipCode;

    @Schema(
            description = "Street address of the diagnostic center.",
            example = "House 12, Road 3",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String address;

    @Schema(
            description = "Road number of the diagnostic center.",
            example = "3",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String roadNo;

    @Schema(
            description = "Holding number of the diagnostic center.",
            example = "12A",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String holdingNo;

    @Schema(
            description = "URL to the profile picture of the diagnostic center.",
            example = "https://example.com/image.jpg",
            accessMode = Schema.AccessMode.READ_WRITE
    )
    private String profilePictureUrl;

    @Schema(
            description = "Primary contact number of the diagnostic center.",
            example = "+8801881264859",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String contactNumber;

    @Schema(
            description = "Email address of the diagnostic center.",
            example = "info@meditech.com",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String email;

    @Schema(
            description = "Operating hours of the diagnostic center.",
            example = "9:00 AM - 9:00 PM",
            accessMode = Schema.AccessMode.READ_WRITE
    )
    private String operatingHours;

    @Schema(
            description = "Accreditation information, if applicable.",
            example = "ISO 15189 Certified",
            accessMode = Schema.AccessMode.READ_WRITE
    )
    private String accreditation;

    @Schema(
            description = "Official website URL of the diagnostic center.",
            example = "https://meditech.com",
            accessMode = Schema.AccessMode.READ_WRITE
    )
    private String websiteUrl;

    @Schema(
            description = "Rating of the diagnostic center based on patient reviews (out of 5).",
            example = "4.5",
            accessMode = Schema.AccessMode.READ_WRITE
    )
    private Double rating;

    @Schema(
            description = "Active status of the diagnostic center.",
            example = "true",
            accessMode = Schema.AccessMode.READ_WRITE
    )
    private Boolean isActive;
}
